Repository Mergifyio/pytest-mergify, pull requests merged in 2025-03, with the labels that each got.

#95 chore: add new attributes
  pytest_mergify/resources/github_actions.py
  tests/test_resources.py
Labels: queued

#98 feat: support for MERGIFY_TEST_JOB_NAME
  pytest_mergify/resources/mergify.py
  pytest_mergify/tracer.py
  tests/test_resources.py
Labels: queued, skip changelog

#100 feat: include skipped tests
  pytest_mergify/__init__.py
  tests/test_spans.py
Labels: skip changelog
